openapi: 3.1.0
info:
  version: 1.0.0
  title: Task Pro
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of a Task Pro app
tags:
  - name: Auth
    description: Auth operations.
  - name: Users
    description: User profile and setings operations
  - name: Boards
    description: Operations for managing boards
  - name: Columns
    description: Operations for managing columns
  - name: Cards
    description: Operations for managing cards
  - name: Help
    description: Possibility of sending a help request to address edik.kozelsky@gmail.com
servers:
  - url: http://localhost:3000
  - url: https://taskpro-backend-y1x7.onrender.com
paths:
  /cards:
    post:
      $ref: '../docs/swagger/path/cards/post.yaml'
    get:
      $ref: '../docs/swagger/path/cards/get.yaml'
  /cards/{id}:
    get:
      $ref: '../docs/swagger/path/cards/{id}/get.yaml'
    patch:
      $ref: '../docs/swagger/path/cards/{id}/patch.yaml'
    delete:
      $ref: '../docs/swagger/path/cards/{id}/delete.yaml'
  /columns:
    get:
      $ref: '../docs/swagger/path/columns/get.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
